### ISSUE TITLE
Idea: FastjsAjax return promise

### ISSUE THREAD

**Issue by dy-xiaodong2022** [fastjs-team/fastjs-next#39]
This is a todo create by dev team.

**Comment by mlmdflr** [comment]
是否考虑将xhr替换成fetch或者额外提供一个fetch的实现

**Comment by dy-xiaodong2022** [comment]
> 是否考虑将xhr替换成fetch或者额外提供一个fetch的实现

目前没有这个打算，现在在做的是让FastjsAjax可以选择性的返回一个Promise，因为有很多人提过这个意见，这个点我也会考虑一下，你可以单独开一个Idea的issue，后期如果有消息就会在你新开的issue下回复，谢谢你的建议

**Comment by dy-xiaodong2022** [comment]
这个功能已经添加，请前往 issue #48 来获取更多资讯

This enhancement has been added, see issue #48 for more info
