### ISSUE TITLE
Idea: Selecter or Selector

### ISSUE THREAD

**Issue by dy-xiaodong2022** [fastjs-team/fastjs-next#41]
We are considering renaming selector to selector, this change may take effect in v1.2.0, but we are still undecided

我们正在考虑将selecter更名为selector，这个变更可能会在v1.2.0中生效，但我们目前仍未决定

**Comment by AkaraChen** [comment]
建议俩都留着，其中一个作为另一个的 alias，在下个大版本 remove

**Comment by so1ve** [comment]
感觉selecter是个typo啊，可以像上面说的那样弄一个alias

**Comment by dy-xiaodong2022** [comment]
> 建议俩都留着，其中一个作为另一个的 alias，在下个大版本 remove

感谢，如果没其他情况的话应该会在下个版本加一个selector的函数的

**Comment by dy-xiaodong2022** [comment]
This problem has been solved.
