### ISSUE TITLE
Idea: 为 fastJsArray 添加模板参数支持

### ISSUE THREAD

**Issue by FurryR** [fastjs-team/fastjs-next#42]
我是一个 14 岁的程序员，刚刚注册 v2ex 账户，并且看到了这个 v2ex 的帖子，非常感兴趣。

但是，我发现 fastJsArray 中使用了 any。any 可能导致在 tsconfig 采用严格的设定时无法通过编译。

是否需要采用模板参数来代替 any？由于我不是很了解 fastJsArray 的作用，所以无法准确地提供进一步的信息。

**Comment by FurryR** [comment]
顺便一提，这个改动不会影响到生成的 Javascript 代码。

**Comment by dy-xiaodong2022** [comment]
你好，模板语法目前并不是非常适用于你说的位置，传递的第一个参数是一个数组，而这个数组内存储的元素类型是不限的，因此目前使用了 `Array<any>`

如果你对此有不同的看法/关于此问题的补充，可以在24小时内发表回复

**Comment by AkaraChen** [comment]
他的意思是叫你加个泛型。。。

**Comment by dy-xiaodong2022** [comment]
昨天有人发了pr，但推的是main分支，就驳回了，如果长期没有再次推送的话我就直接拉他代码，注明作者重新推了

**Comment by dy-xiaodong2022** [comment]
This idea has been added in commit e08d6687c0fb86923206e6108a0f5157497f30c6
And it will be added at version v1.2.0
