### ISSUE TITLE
Idea: 解决 Frame 和 Library 混用的问题

### ISSUE THREAD

**Issue by dy-xiaodong2022** [fastjs-team/fastjs-next#44]
解决在文档，项目描述等位置专业名词Frame 和 Library 混用的问题

**Comment by AkaraChen** [comment]
也没有可能，在前端领域我们框架一般用 Framework。

而且你目前的封装程度...真的好意思叫框架吗？

**Comment by dy-xiaodong2022** [comment]
> 有没有可能，在前端领域我们框架一般用 `Framework`。
> 
> 而且你目前的封装程度...真的好意思叫框架吗？

发布这个issue的主要目的就是将frame改为library，因为frame只是这个项目的目标，而从目前来看，只能算library

**Comment by FurryR** [comment]
frame 的意思是 帧，framework 的意思才是框架。请好好学学英语。

**Comment by dy-xiaodong2022** [comment]
> frame 的意思是 帧，framework 的意思才是框架。请好好学学英语。

应该也可以解成框架吧

![图片](https://user-images.githubusercontent.com/84657208/210136599-6676a8ca-0ef5-462f-ae60-a69cf267f0ec.png)
