### ISSUE TITLE
Idea: 建议把Ajax改成Promise

### ISSUE THREAD

**Issue by Groupguanfang** [fastjs-team/fastjs-next#48]
如题，把Ajax套层Promise吧😂原生Ajax设计缺陷众所周知了已经

**Comment by dy-xiaodong2022** [comment]
这个很快就会加的，然后方式倾向于两者并存，主要的就是返回Promise，但开发者还是可以选择在config中传递callback，failed

**Comment by dy-xiaodong2022** [comment]
你好，这个功能已经在21cb14c1d0648b96cd2f7598553d282110ba6b04增加，这个功能将会于版本v1.2.0发布

This idea has been added in 21cb14c1d0648b96cd2f7598553d282110ba6b04
And it will publish at release version v1.2.0
